# Generated by Django 4.0.6 on 2022-07-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_book_category_role_userrole_reservebook_issuebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservebook',
            name='issue_date',
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='date_return',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bookcategory',
            unique_together={('book_id', 'category_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user_id', 'role_name')},
        ),
        migrations.RemoveField(
            model_name='bookcategory',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='issue_date',
        ),
    ]
