# Generated by Django 4.0.6 on 2022-07-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0005_remove_reservebook_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='date_return',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
