# Generated by Django 4.0.6 on 2022-07-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0007_alter_issuebook_date_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='date_return',
            field=models.DateTimeField(null=True),
        ),
    ]
