# Generated by Django 4.0.6 on 2022-07-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0008_alter_issuebook_date_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
    ]
