# Generated by Django 4.0.6 on 2022-07-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0010_reservebook_is_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservebook',
            name='is_reserved',
        ),
    ]
