# Generated by Django 4.0.6 on 2022-07-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0011_remove_reservebook_is_reserved'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservebook',
            unique_together={('user_id', 'book_id')},
        ),
    ]
