# Generated by Django 4.0.6 on 2022-07-21 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0012_alter_reservebook_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='user_name',
            field=models.ForeignKey(db_column='username', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='username_fk', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='issuebook',
            unique_together={('user_id', 'book_id')},
        ),
    ]
