# Generated by Django 4.0.6 on 2022-07-21 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0013_userrole_user_name_alter_issuebook_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='user_name',
            field=models.ForeignKey(db_column='username', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='username_fk', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
