# Generated by Django 4.0.6 on 2022-07-21 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0015_alter_userrole_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='user_name',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='username_fk', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
