# Generated by Django 4.0.6 on 2022-07-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0017_alter_userrole_unique_together_alter_userrole_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='user_name',
        ),
    ]
