# Generated by Django 4.0.6 on 2022-07-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0019_alter_userrole_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='category_name',
            field=models.ForeignKey(db_column='category_name', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookcategory_categoryfk', to='lmsapp.category', to_field='name'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bookcategory',
            unique_together={('book_id', 'category_name')},
        ),
        migrations.RemoveField(
            model_name='bookcategory',
            name='category_id',
        ),
    ]
