# Generated by Django 4.0.6 on 2022-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0020_alter_bookcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_issued',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='is_reserved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
