# Generated by Django 4.0.6 on 2022-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0021_book_is_issued_book_is_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
