# Generated by Django 4.0.6 on 2022-07-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0022_alter_book_is_issued_alter_book_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='fine',
            field=models.IntegerField(null=True),
        ),
    ]
