# Generated by Django 4.0.6 on 2022-07-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0023_issuebook_fine'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issuebook',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='reservebook',
            unique_together=set(),
        ),
    ]
