# Generated by Django 4.0.6 on 2022-07-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0024_alter_issuebook_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='fine',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
