# Generated by Django 4.0.6 on 2022-07-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0025_alter_issuebook_fine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='date_return',
            new_name='date_returned',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
