# Generated by Django 4.0.6 on 2022-07-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0026_rename_date_return_issuebook_date_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservebook',
            name='date_issue',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
