# Generated by Django 4.0.6 on 2022-07-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0027_reservebook_date_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservebook',
            name='date_issue',
            field=models.DateTimeField(null=True),
        ),
    ]
