# Generated by Django 4.0.6 on 2022-07-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0031_alter_reservebook_date_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservebook',
            name='date_issue',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
