# Generated by Django 4.0.6 on 2022-07-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0033_rename_date_issue_reservebook_issue_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role_name',
            field=models.ForeignKey(db_column='role_name', default='Student', on_delete=django.db.models.deletion.CASCADE, related_name='book_fk', to='lmsapp.role', to_field='name'),
        ),
    ]
